version: '3.5'

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school_db
      MYSQL_USER: school
      MYSQL_PASSWORD: school_pass
    ports:
      - "3306:3306"

  app_service:
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"